version: '3.8'

services:

  api:
    image: murilloxz/vital:latest
    container_name: vital-api
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MONGODB_CONNECTION_STRING: mongodb://mongo:123456@mongodb:27017/RegistrosDosProntuarios
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network
    pull_policy: always 

  mongodb:
    image: mongo:latest
    container_name: db-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: RegistrosDosProntuarios
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
